// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getHost(args?: GetHostArgs, opts?: pulumi.InvokeOptions): Promise<GetHostResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zabbix:index/getHost:getHost", {
        "enabled": args.enabled,
        "host": args.host,
        "hostid": args.hostid,
        "inventoryMode": args.inventoryMode,
        "macros": args.macros,
        "name": args.name,
        "tags": args.tags,
        "templates": args.templates,
    }, opts);
}

/**
 * A collection of arguments for invoking getHost.
 */
export interface GetHostArgs {
    enabled?: boolean;
    host?: string;
    hostid?: string;
    inventoryMode?: string;
    macros?: inputs.GetHostMacro[];
    name?: string;
    tags?: inputs.GetHostTag[];
    templates?: string[];
}

/**
 * A collection of values returned by getHost.
 */
export interface GetHostResult {
    readonly enabled?: boolean;
    readonly groups: string[];
    readonly host: string;
    readonly hostid?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly interfaces: outputs.GetHostInterface[];
    readonly inventories: outputs.GetHostInventory[];
    readonly inventoryMode?: string;
    readonly macros: outputs.GetHostMacro[];
    readonly name: string;
    readonly proxyid: string;
    readonly tags?: outputs.GetHostTag[];
    readonly templates: string[];
}
export function getHostOutput(args?: GetHostOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetHostResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zabbix:index/getHost:getHost", {
        "enabled": args.enabled,
        "host": args.host,
        "hostid": args.hostid,
        "inventoryMode": args.inventoryMode,
        "macros": args.macros,
        "name": args.name,
        "tags": args.tags,
        "templates": args.templates,
    }, opts);
}

/**
 * A collection of arguments for invoking getHost.
 */
export interface GetHostOutputArgs {
    enabled?: pulumi.Input<boolean>;
    host?: pulumi.Input<string>;
    hostid?: pulumi.Input<string>;
    inventoryMode?: pulumi.Input<string>;
    macros?: pulumi.Input<pulumi.Input<inputs.GetHostMacroArgs>[]>;
    name?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<inputs.GetHostTagArgs>[]>;
    templates?: pulumi.Input<pulumi.Input<string>[]>;
}
