// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getHostgroup(args: GetHostgroupArgs, opts?: pulumi.InvokeOptions): Promise<GetHostgroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zabbix:index/getHostgroup:getHostgroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getHostgroup.
 */
export interface GetHostgroupArgs {
    name: string;
}

/**
 * A collection of values returned by getHostgroup.
 */
export interface GetHostgroupResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getHostgroupOutput(args: GetHostgroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetHostgroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zabbix:index/getHostgroup:getHostgroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getHostgroup.
 */
export interface GetHostgroupOutputArgs {
    name: pulumi.Input<string>;
}
