// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getProxy(args: GetProxyArgs, opts?: pulumi.InvokeOptions): Promise<GetProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zabbix:index/getProxy:getProxy", {
        "host": args.host,
    }, opts);
}

/**
 * A collection of arguments for invoking getProxy.
 */
export interface GetProxyArgs {
    host: string;
}

/**
 * A collection of values returned by getProxy.
 */
export interface GetProxyResult {
    readonly host: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getProxyOutput(args: GetProxyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProxyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("zabbix:index/getProxy:getProxy", {
        "host": args.host,
    }, opts);
}

/**
 * A collection of arguments for invoking getProxy.
 */
export interface GetProxyOutputArgs {
    host: pulumi.Input<string>;
}
