// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class LldSimple extends pulumi.CustomResource {
    /**
     * Get an existing LldSimple resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LldSimpleState, opts?: pulumi.CustomResourceOptions): LldSimple {
        return new LldSimple(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'zabbix:index/lldSimple:LldSimple';

    /**
     * Returns true if the given object is an instance of LldSimple.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LldSimple {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LldSimple.__pulumiType;
    }

    public readonly conditions!: pulumi.Output<outputs.LldSimpleCondition[] | undefined>;
    /**
     * LLD Delay period
     */
    public readonly delay!: pulumi.Output<string | undefined>;
    /**
     * EvalType, one of: andor, and, or, custom
     */
    public readonly evaltype!: pulumi.Output<string | undefined>;
    /**
     * Formula
     */
    public readonly formula!: pulumi.Output<string | undefined>;
    /**
     * Host ID
     */
    public readonly hostid!: pulumi.Output<string>;
    /**
     * Host Interface ID
     */
    public readonly interfaceid!: pulumi.Output<string | undefined>;
    /**
     * LLD KEY
     */
    public readonly key!: pulumi.Output<string>;
    /**
     * LLD Stale Item Lifetime
     */
    public readonly lifetime!: pulumi.Output<string | undefined>;
    public readonly macros!: pulumi.Output<outputs.LldSimpleMacro[] | undefined>;
    /**
     * LLD Name
     */
    public readonly name!: pulumi.Output<string>;
    public readonly preprocessors!: pulumi.Output<outputs.LldSimplePreprocessor[] | undefined>;

    /**
     * Create a LldSimple resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LldSimpleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LldSimpleArgs | LldSimpleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LldSimpleState | undefined;
            resourceInputs["conditions"] = state ? state.conditions : undefined;
            resourceInputs["delay"] = state ? state.delay : undefined;
            resourceInputs["evaltype"] = state ? state.evaltype : undefined;
            resourceInputs["formula"] = state ? state.formula : undefined;
            resourceInputs["hostid"] = state ? state.hostid : undefined;
            resourceInputs["interfaceid"] = state ? state.interfaceid : undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["lifetime"] = state ? state.lifetime : undefined;
            resourceInputs["macros"] = state ? state.macros : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["preprocessors"] = state ? state.preprocessors : undefined;
        } else {
            const args = argsOrState as LldSimpleArgs | undefined;
            if ((!args || args.hostid === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hostid'");
            }
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            resourceInputs["conditions"] = args ? args.conditions : undefined;
            resourceInputs["delay"] = args ? args.delay : undefined;
            resourceInputs["evaltype"] = args ? args.evaltype : undefined;
            resourceInputs["formula"] = args ? args.formula : undefined;
            resourceInputs["hostid"] = args ? args.hostid : undefined;
            resourceInputs["interfaceid"] = args ? args.interfaceid : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["lifetime"] = args ? args.lifetime : undefined;
            resourceInputs["macros"] = args ? args.macros : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["preprocessors"] = args ? args.preprocessors : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LldSimple.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LldSimple resources.
 */
export interface LldSimpleState {
    conditions?: pulumi.Input<pulumi.Input<inputs.LldSimpleCondition>[]>;
    /**
     * LLD Delay period
     */
    delay?: pulumi.Input<string>;
    /**
     * EvalType, one of: andor, and, or, custom
     */
    evaltype?: pulumi.Input<string>;
    /**
     * Formula
     */
    formula?: pulumi.Input<string>;
    /**
     * Host ID
     */
    hostid?: pulumi.Input<string>;
    /**
     * Host Interface ID
     */
    interfaceid?: pulumi.Input<string>;
    /**
     * LLD KEY
     */
    key?: pulumi.Input<string>;
    /**
     * LLD Stale Item Lifetime
     */
    lifetime?: pulumi.Input<string>;
    macros?: pulumi.Input<pulumi.Input<inputs.LldSimpleMacro>[]>;
    /**
     * LLD Name
     */
    name?: pulumi.Input<string>;
    preprocessors?: pulumi.Input<pulumi.Input<inputs.LldSimplePreprocessor>[]>;
}

/**
 * The set of arguments for constructing a LldSimple resource.
 */
export interface LldSimpleArgs {
    conditions?: pulumi.Input<pulumi.Input<inputs.LldSimpleCondition>[]>;
    /**
     * LLD Delay period
     */
    delay?: pulumi.Input<string>;
    /**
     * EvalType, one of: andor, and, or, custom
     */
    evaltype?: pulumi.Input<string>;
    /**
     * Formula
     */
    formula?: pulumi.Input<string>;
    /**
     * Host ID
     */
    hostid: pulumi.Input<string>;
    /**
     * Host Interface ID
     */
    interfaceid?: pulumi.Input<string>;
    /**
     * LLD KEY
     */
    key: pulumi.Input<string>;
    /**
     * LLD Stale Item Lifetime
     */
    lifetime?: pulumi.Input<string>;
    macros?: pulumi.Input<pulumi.Input<inputs.LldSimpleMacro>[]>;
    /**
     * LLD Name
     */
    name?: pulumi.Input<string>;
    preprocessors?: pulumi.Input<pulumi.Input<inputs.LldSimplePreprocessor>[]>;
}
