// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("zabbix");

/**
 * Zabbix API password
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Serialize API requests, if required due to API race conditions
 */
export declare const serialize: boolean | undefined;
Object.defineProperty(exports, "serialize", {
    get() {
        return __config.getObject<boolean>("serialize");
    },
    enumerable: true,
});

/**
 * Disable TLS certificate checking (for testing use only)
 */
export declare const tlsInsecure: boolean | undefined;
Object.defineProperty(exports, "tlsInsecure", {
    get() {
        return __config.getObject<boolean>("tlsInsecure");
    },
    enumerable: true,
});

/**
 * Zabbix API url
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

/**
 * Zabbix API username
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

